### ISSUE TITLE
Cannot add sign to a gauge value

### ISSUE THREAD

**Issue by alexsegura** [BedrockStreaming/Statsd#25]
It is actually possible to add a `+/-` to a gauge 

> Adding a sign to the gauge value will change the value, rather than setting it.
https://github.com/etsy/statsd/blob/master/docs/metric_types.md#gauges

But it impossible with the component because: 
- the `addToSend` method [casts $value as `int`
](https://github.com/M6Web/Statsd/blob/d705e9d53936d689df1893e449a25944524d1ade/src/M6Web/Component/Statsd/Client.php#L144)
- there is a check in `MessageEntity` to [verify that `$value` is an `init`](https://github.com/M6Web/Statsd/blob/d705e9d53936d689df1893e449a25944524d1ade/src/M6Web/Component/Statsd/MessageEntity.php#L73)

I can still use the `writeDatas` method directly but this is not satisfying. 

This should definitely be supported by the client, as this is a valid StatsD message. 
I think this can be implemented quite easily, without any BC breaks. 

I can submit a pull request.

**Comment by Oliboy50** [comment]
Hello @alexsegura 

it seems that you're totally right, thanks to mention that.

Your pull request would be really appreciated :)
